# Generated by Django 4.2.4 on 2023-09-30 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='your_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
