# Generated by Django 4.2.4 on 2023-09-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_todo_your_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='your_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
