# Generated by Django 4.2.6 on 2023-10-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_todo_your_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
